version: 1
disable_existing_loggers: false

formatters:
  verbose:
    format: '%(levelname)s:%(name)s:%(funcName)s:%(lineno)d: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: verbose

root:
  level: INFO
  handlers: [console]

loggers:
  west:
    level: DEBUG
    handlers: [ console ]
